// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/audio.tsx";
import * as $3 from "./routes/api/chat.tsx";
import * as $4 from "./routes/api/fetchHistory.tsx";
import * as $5 from "./routes/api/fetchStoredUrl.tsx";
import * as $6 from "./routes/auth.ts";
import * as $7 from "./routes/history.ts";
import * as $8 from "./routes/index.tsx";
import * as $$0 from "./islands/UnifiedIsland/AudioPlayer.ts";
import * as $$1 from "./islands/UnifiedIsland/CharacterSelection.ts";
import * as $$2 from "./islands/UnifiedIsland/History.ts";
import * as $$3 from "./islands/UnifiedIsland/InputField.ts";
import * as $$4 from "./islands/UnifiedIsland/SubjectCard.ts";
import * as $$5 from "./islands/UnifiedIsland/UnifiedIsland.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/audio.tsx": $2,
    "./routes/api/chat.tsx": $3,
    "./routes/api/fetchHistory.tsx": $4,
    "./routes/api/fetchStoredUrl.tsx": $5,
    "./routes/auth.ts": $6,
    "./routes/history.ts": $7,
    "./routes/index.tsx": $8,
  },
  islands: {
    "./islands/UnifiedIsland/AudioPlayer.ts": $$0,
    "./islands/UnifiedIsland/CharacterSelection.ts": $$1,
    "./islands/UnifiedIsland/History.ts": $$2,
    "./islands/UnifiedIsland/InputField.ts": $$3,
    "./islands/UnifiedIsland/SubjectCard.ts": $$4,
    "./islands/UnifiedIsland/UnifiedIsland.tsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
